### ISSUE TITLE
TableSortLabel should not be hidden when mouse is not hovering on it

### ISSUE THREAD

**Issue by huayunh** [brightlayer-ui/react-themes#11]
## Describe the desired behavior

When a `.MuiTableSortLabel` is not hovered on, the arrow should have the ~disabled color~ 
(edit: should be a "disabledBackground" color of Gray500@12% for light theme, and a Black200@24% for dark theme). 

When it is hovered or in-use, the label should be `text.secondary`

## Describe the current behavior

The arrow has an opacity 0 on it when not in use.

![image](https://user-images.githubusercontent.com/8997218/138380152-012e9638-d1ad-4024-9529-728bc2ab3fb2.png)

## Additional Context

This will be part of the Tables effort.

**Comment by huayunh** [comment]
2633

**Comment by bkarambe** [comment]
@huayunh Shall we close this, as PR has been merged?
