### ISSUE TITLE
Remove table alternating row color

### ISSUE THREAD

**Issue by huayunh** [brightlayer-ui/react-themes#16]
#### Describe the desired behavior

Make the alternating row color optional. Different projects have different needs.

#### Describe the current behavior

It alternates.

**Comment by emclaug2** [comment]
Doublecheck angular has zebra striking on by default.

**Comment by joebochill** [comment]
Either:
1) update the Readme to show an example of how to disable zebra striping or
2) disable the zebra striping and update the readme to show an example of how to turn it on

Go with whichever approach is going to be the least amount of effort to maintain consistency across frameworks and the defaults from Material UI and Angular Material.

**Comment by emclaug2** [comment]
Fixed in #25
