### ISSUE TITLE
Fix divider color

### ISSUE THREAD

**Issue by ektasawant** [brightlayer-ui/react-themes#17]
#### Describe the bug
Divider color of InfoListItem is not correct.

#### What is the expected behavior?
Divider colors are defined to be:
Light theme: black 500, 12%. i.e., rgba(66, 78, 84, 12%)
Dark theme: black200, 36%. i.e., rgba(161, 167,170, 36%)

#### What are the steps to reproduce?
1. Go to https://pxblue-components.github.io/react/?path=/story/components-info-list-item--within-full-list
2. Observe divider styling

#### Screenshots or links to minimum reproduction example
Light theme:
<img width="323" alt="Screenshot 2021-12-08 at 3 53 07 PM" src="https://user-images.githubusercontent.com/10433274/145192114-e7277014-f837-463f-a53e-112c501d7519.png">

Dark theme is correct:
<img width="304" alt="Screenshot 2021-12-08 at 3 56 16 PM" src="https://user-images.githubusercontent.com/10433274/145192369-02fb3c9d-557b-4ea7-a84a-cc42bb4b946c.png">

####
Environment
All

**Comment by emclaug2** [comment]
Doublecheck this issue is happening within the showcase demo.

**Comment by joebochill** [comment]
We should be able to simply update the global divider style in the theme
