### ISSUE TITLE
Outlined Select component bleeds through

### ISSUE THREAD

**Issue by huayunh** [brightlayer-ui/react-themes#19]
### Describe the bug

Outline borders are bleeding into labels. This is the case for both light and dark theme.

However, the outlined text fields are fine by themselves.

#### What is the expected behavior?

It should behave.

#### What are the steps to reproduce?
1. yarn start the showcase
2. Go to http://localhost:3000/material-ui-components/input-components
3. Click on an outlined select

#### Screenshots or links to minimum reproduction example

https://user-images.githubusercontent.com/8997218/149216664-ebf4c3ce-ea48-4b5f-a743-f1d2b1a73b58.mov

**Comment by huayunh** [comment]
This might be a MUI thing; you guys know how strict I am when it comes to these styling... pretty confident that I don't usually miss things this obvious

**Comment by emclaug2** [comment]
Before making any code changes, test the showcase demo without the BLUI theme applied to make sure the issue is on us and not MUI.

**Comment by jeffvg** [comment]
https://github.com/brightlayer-ui/react-showcase-demo/pull/32
