### ISSUE TITLE
Change Default Tooltip FontSize

### ISSUE THREAD

**Issue by emclaug2** [brightlayer-ui/react-themes#8]
#### Describe the desired behavior
Tooltip font size should be 12dp by default.

#### Describe the current behavior
It is not 12dp currently. 

#### Is this request related to a current issue?
No

#### Additional Context

This was observed in this PR: https://github.com/pxblue/react-design-patterns/pull/78

**Comment by jeffvg** [comment]
low priority for R21 Q3
